name: CI/CD Deployment to GKE

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID}}
    SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_KEY}}
    GKE_CLUSTER: "powerful-clusters"
    GKE_REGION: "us-central1-a"
    DEPLOYMENT_NAME: "mlops-app"
    REPOSITORY: "us-central1-docker.pkg.dev/encoded-joy-418604/my-repo"
    IMAGE_NAME: "us-central1-docker.pkg.dev/encoded-joy-418604/my-repo/mlops-app"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        container:
            image: google/cloud-sdk:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_SERVICE_KEY}}

            - name: Configure GCloud
              run: |
                gcloud config set project $PROJECT_ID
                gcloud auth configure-docker us-central1-docker.pkg.dev

            - name: Build and Push Image
              run: |
                apt-get update && apt-get install -y docker.io
                docker build -t $IMAGE_NAME:$GITHUB_SHA .
                docker push $IMAGE_NAME:$GITHUB_SHA

            - name: GKE Configuration
              run: |
                gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

            - name: Deploy to Kubernetes
              run: |
                kubectl apply -f kubernetes-deployment.yaml
                kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE_NAME:$GITHUB_SHA
